enum token {
    CLASS, INHERITS, IF, THEN, ELSE, FI, WHILE, LOOP, POOL, LET, IN,
    OUT_STRING, OUT_INT, TRUE, FALSE, INT_CONST, STR_CONST, ID,
    ASSIGN, PLUS, MINUS, MULT, DIV, LT, LE, EQ, NOT, ISVOID, NEW,
    SEMI, COLON, COMMA, LPAREN, RPAREN, LBRACE, RBRACE, DOT, AT,
    ERROR, END_OF_FILE
};
